name: DisplayTest
main: io.github.haburashi76.display.plugin.DisplayTestPlugin
version: 1.0
commands:
  summon-displays:
    description: test
  shoot-projectile:
    description: test
libraries:
  - io.github.haburashi76:display-core:1.0.7